services:
  # PHP + Laravel
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: lar_app
    volumes:
      - ./app:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - laravel_network

  # PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    networks:
      - laravel_network

  # Nginx
  webserver:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8200:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

volumes:
  postgres_data:

networks:
  laravel_network:
    driver: bridge